title: Euruko 2027
description: >-
  Euruko 2027, the European Ruby conference, in Modena, Italy.
baseurl: ""
url: "https://2027.euruko.org"

plugins:
  - jekyll-feed

exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
